[package]
name = "longlens"
version = "0.2.0"
edition = "2024"

[dependencies]
gettext-rs = { version = "0.7", features = ["gettext-system"] }
gtk = { version = "0.11", package = "gtk4", features = ["v4_22"] }
gdk = { version = "0.11", package = "gdk4", features = ["v4_22"] }
adw = { version = "0.9.1", package = "libadwaita", features = ["v1_9"] }
ironrdp-client = { git = "https://github.com/Devolutions/IronRDP", rev = "3905d177f2417d0e810b437d7e3ee0a7e954c6cc" }
ironrdp = { git = "https://github.com/Devolutions/IronRDP", rev = "3905d177f2417d0e810b437d7e3ee0a7e954c6cc", features = ["input", "connector", "cliprdr"] }
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7" }
softbuffer = "0.4"

# Logging
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }

#Utils
anyhow = "1"
keycode = "1"
semver = "1"
tap = "1"
whoami = "1.6"
async-channel = "2.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1", features = ["v4"] }
smallvec = "1.15"
secret-service = { version = "5", features = ["rt-tokio-crypto-rust"] }
secrecy = "0.8"

