[package]
name = "fernsicht-rdp"
version = "0.1.0"
edition = "2024"

[dependencies]
gettext-rs = { version = "0.7", features = ["gettext-system"] }
gtk = { version = "0.9", package = "gtk4", features = ["gnome_47"] }
adw = { version = "0.7", package = "libadwaita", features = ["v1_6"] }
ironrdp = { version = "0.13", features = [
    "session",
    "input",
    "graphics",
    "dvc",
    "svc",
    "rdpdr",
    "rdpsnd",
    "cliprdr",
    "displaycontrol",
    "connector",
] }
ironrdp-core = { version = "0.1", features = ["alloc"] }
ironrdp-tls = { version = "0.1", features = ["rustls"] }
ironrdp-tokio = { version = "0.7", features = ["reqwest"] }
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7" }
softbuffer = "0.4"

# Logging
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = "0.3.20"

#Utils
anyhow = "1"
semver = "1"
tap = "1"
whoami = "1.6"
async-channel = "2.5.0"

