name: CI
on:
  push:
    branches: [main]
    tags: ['v*']
permissions:
  contents: read
  packages: write
  pages: write
  id-token: write
jobs:
  publish:
    uses: aetherpak/actions/.github/workflows/publish.yml@v3
    with:
      manifest-path: ${{ startsWith(github.ref, 'refs/tags/v') && 'de.f1ori.longlens.json' || 'de.f1ori.longlens.Devel.json' }}
    secrets:
      gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}