name: Publish Flatpak
on: { push: { branches: [main] } }
permissions:
  contents: read
  packages: write
  pages: write
  id-token: write
jobs:
  publish:
    uses: aetherpak/actions/.github/workflows/publish.yml@v3
    with:
      manifest-path: de.f1ori.longlens.Devel.json
      run-linter: false
    secrets:
      gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}